import type { EventLogEntry } from "./app-events.ts";
import type { CompactionStatus } from "./app-tool-stream.ts";
import type { DevicePairingList } from "./controllers/devices.ts";
import type { ExecApprovalRequest } from "./controllers/exec-approval.ts";
import type { ExecApprovalsFile, ExecApprovalsSnapshot } from "./controllers/exec-approvals.ts";
import type { ChatSessionResources } from "./chat/chat-resources.ts";
import type { SkillMessage } from "./controllers/skills.ts";
import type { GatewayBrowserClient, GatewayHelloOk } from "./gateway.ts";
import type { Tab } from "./navigation.ts";
import type { UiSettings } from "./storage.ts";
import type { ThemeTransitionContext } from "./theme-transition.ts";
import type { ThemeMode } from "./theme.ts";
import type {
  AgentsListResult,
  AgentsFilesListResult,
  AgentIdentityResult,
  ChannelsStatusSnapshot,
  ConfigSnapshot,
  ConfigUiHints,
  CronJob,
  CronRunLogEntry,
  CronStatus,
  HealthSnapshot,
  LogEntry,
  LogLevel,
  NostrProfile,
  PresenceEntry,
  SessionsUsageResult,
  CostUsageSummary,
  SessionsListResult,
  SkillStatusReport,
  StatusSummary,
} from "./types.ts";
import type { ChatAttachment, ChatQueueItem, CronFormState } from "./ui-types.ts";
import type { NostrProfileFormState } from "./views/channels.nostr-profile-form.ts";
import type { NativeDialogModel } from "./views/native-dialog-overlay.ts";

export type AppViewState = {
  settings: UiSettings;
  password: string;
  tab: Tab;
  onboarding: boolean;
  setupWizardActive: boolean;
  setupWizardStepIndex: number;
  setupWizardSession: import("./setup-wizard.ts").SetupWizardSession;
  setupWizardResourceTab: import("./setup-wizard.ts").SetupWizardResourceTab;
  setupWizardModelSearchQuery: string;
  setupWizardModelCategory: import("./views/model-library.ts").ModelLibraryCategory;
  setupWizardEnabledProviders: Set<string>;
  setupWizardResourcesLoading: boolean;
  setupWizardResourcesError: string | null;
  setupWizardSkillItems: import("./controllers/remote-market.ts").SkillListItem[];
  setupWizardSkillQuery: string;
  setupWizardSkillInstallingFolder: string | null;
  setupWizardEmployeeItems: import("./controllers/remote-market.ts").EmployeeListItem[];
  setupWizardEmployeeQuery: string;
  setupWizardEmployeeInstallingId: string | null;
  setupWizardMcpItems: import("./controllers/remote-market.ts").McpListItem[];
  setupWizardMcpQuery: string;
  setupWizardMcpInstallingId: string | null;
  setupWizardBrowserChromiumSelected: boolean;
  setupWizardBrowserReady: boolean;
  setupWizardBrowserInstalling: boolean;
  setupWizardBrowserInstallError: string | null;
  setupWizardBrowserInstallProgress: import("./controllers/browser-install.ts").BrowserInstallProgress | null;
  setupWizardSelectedScenarioId: string | null;
  setupWizardScenarioMenuOpenId: string | null;
  setupWizardScenarioDetailId: string | null;
  setupWizardScenarioEnvPanelOpen: boolean;
  setupWizardSelectedChannelId: string | null;
  setupWizardScenarioRunning: boolean;
  setupWizardScenarioRunCompleted: boolean;
  setupWizardScenarioCancelRequested: boolean;
  setupWizardWelcomeVisible: boolean;
  setupWizardScenarioProgress: import("./setup-wizard.ts").SetupWizardScenarioRunRecord | null;
  setupWizardScenarioEnvPrompt: import("./setup-wizard.ts").SetupWizardScenarioEnvPrompt | null;
  isDesktopShell: boolean;
  isWindowsDesktop: boolean;
  isWindowMaximised: boolean;
  basePath: string;
  connected: boolean;
  theme: ThemeMode;
  themeResolved: "light" | "dark";
  hello: GatewayHelloOk | null;
  lastError: string | null;
  eventLog: EventLogEntry[];
  assistantName: string;
  assistantAvatar: string | null;
  assistantAgentId: string | null;
  sessionKey: string;
  chatLoading: boolean;
  chatSending: boolean;
  chatMessage: string;
  chatComposeHasText: boolean;
  chatComposeClearToken: number;
  chatComposeInsertToken: number;
  chatComposeInsertSnippet: string;
  chatAttachments: ChatAttachment[];
  chatAttachmentError: string | null;
  chatMessages: unknown[];
  chatToolMessages: unknown[];
  chatStream: string | null;
  chatReasoningStream: string | null;
  chatStreamStartedAt: number | null;
  chatA2UIMessages: unknown[];
  chatFilePreview: import("./chat/file-blocks.ts").FilePreviewRequest | null;
  chatRunId: string | null;
  chatTerminalRunIds: string[];
  chatErrorRunId: string | null;
  chatRunPhase: "idle" | "thinking" | "tool" | "streaming";
  compactionStatus: CompactionStatus | null;
  chatAvatarUrl: string | null;
  chatThinkingLevel: string | null;
  chatModelRef: string | null;
  chatResources: ChatSessionResources;
  chatResourcesPanelOpen: boolean;
  chatResourcesTab: "skills" | "mcp";
  chatResourcesSkillSearch: string;
  chatResourcesMcpSearch: string;
  chatExtractSkillLoading: boolean;
  chatExtractSkillError: string | null;
  chatExtractSkillMarkdown: string | null;
  chatExtractSkillFilename: string | null;
  chatExtractSkillOpen: boolean;
  chatQueue: ChatQueueItem[];
  nodesLoading: boolean;
  nodes: Array<Record<string, unknown>>;
  chatNewMessagesBelow: boolean;
  chatConversationOnly: boolean;
  sidebarOpen: boolean;
  sidebarContent: string | null;
  sidebarError: string | null;
  splitRatio: number;
  scrollToBottom: () => void;
  devicesLoading: boolean;
  devicesError: string | null;
  devicesList: DevicePairingList | null;
  execApprovalsLoading: boolean;
  execApprovalsSaving: boolean;
  execApprovalsDirty: boolean;
  execApprovalsSnapshot: ExecApprovalsSnapshot | null;
  execApprovalsForm: ExecApprovalsFile | null;
  execApprovalsSelectedAgent: string | null;
  execApprovalsTarget: "gateway" | "node";
  execApprovalsTargetNodeId: string | null;
  execApprovalQueue: ExecApprovalRequest[];
  execApprovalBusy: boolean;
  execApprovalError: string | null;
  pendingGatewayUrl: string | null;
  configLoading: boolean;
  configRaw: string;
  configRawOriginal: string;
  configValid: boolean | null;
  configIssues: unknown[];
  configSaving: boolean;
  configApplying: boolean;
  updateRunning: boolean;
  applySessionKey: string;
  configSnapshot: ConfigSnapshot | null;
  configSchema: unknown;
  configSchemaVersion: string | null;
  configSchemaLoading: boolean;
  configUiHints: ConfigUiHints;
  configForm: Record<string, unknown> | null;
  configFormOriginal: Record<string, unknown> | null;
  configFormMode: "form" | "raw";
  configSearchQuery: string;
  configActiveSection: string | null;
  configActiveSubsection: string | null;
  channelsLoading: boolean;
  channelsSnapshot: ChannelsStatusSnapshot | null;
  channelsError: string | null;
  channelsLastSuccess: number | null;
  channelsSelectedChannelId: string | null;
  whatsappLoginMessage: string | null;
  whatsappLoginQrDataUrl: string | null;
  whatsappLoginConnected: boolean | null;
  whatsappBusy: boolean;
  weworkQrModalOpen: boolean;
  weworkQrModalLoading: boolean;
  weworkQrModalPolling: boolean;
  weworkQrModalSuccess: boolean;
  weworkQrModalError: string | null;
  weworkQrModalReplaceWarn: boolean;
  weworkQrModalAuthUrl: string | null;
  weworkQrModalGenPageUrl: string | null;
  weixinQrModalOpen: boolean;
  weixinQrModalLoading: boolean;
  weixinQrModalPolling: boolean;
  weixinQrModalSuccess: boolean;
  weixinQrModalError: string | null;
  weixinQrModalReplaceWarn: boolean;
  weixinQrModalImageSrc: string | null;
  weixinQrModalScanPageUrl: string | null;
  weixinQrModalScanned: boolean;
  weixinQrPollAbort: boolean;
  weixinQrSuccessCloseTimer: number | null;
  weixinQrSessionQrcode: string;
  weixinQrSessionBaseUrl: string;
  weixinQrSessionBotType: string;
  nativeDialog: NativeDialogModel;
  nativePromptInput: string;
  nostrProfileFormState: NostrProfileFormState | null;
  nostrProfileAccountId: string | null;
  configFormDirty: boolean;
  presenceLoading: boolean;
  presenceEntries: PresenceEntry[];
  presenceError: string | null;
  presenceStatus: string | null;
  agentsLoading: boolean;
  agentsList: AgentsListResult | null;
  agentsError: string | null;
  agentsSelectedId: string | null;
  agentsPanel: "overview" | "files" | "tools" | "skills" | "channels" | "cron";
  agentFilesLoading: boolean;
  agentFilesError: string | null;
  agentFilesList: AgentsFilesListResult | null;
  agentFileContents: Record<string, string>;
  agentFileDrafts: Record<string, string>;
  agentFileActive: string | null;
  agentFileSaving: boolean;
  agentIdentityLoading: boolean;
  agentIdentityError: string | null;
  agentIdentityById: Record<string, AgentIdentityResult>;
  agentSkillsLoading: boolean;
  agentSkillsError: string | null;
  agentSkillsReport: SkillStatusReport | null;
  agentSkillsAgentId: string | null;
  sessionsLoading: boolean;
  sessionsResult: SessionsListResult | null;
  sessionEditingKey: string | null;
  /** 消息页侧栏：⋯ 菜单（fixed 浮层，避免被侧栏 overflow 裁剪） */
  sessionOverflow: { top: number; right: number; key: string } | null;
  /** 消息页侧栏：按名称 / 标签字段 / 副标题等模糊过滤会话 */
  sessionSidebarQuery: string;
  sessionsError: string | null;
  sessionsFilterActive: string;
  sessionsFilterLimit: string;
  sessionsIncludeGlobal: boolean;
  sessionsIncludeUnknown: boolean;
  sessionsBulkMode: boolean;
  sessionsSelectedKeys: string[];
  usageLoading: boolean;
  usageResult: SessionsUsageResult | null;
  usageCostSummary: CostUsageSummary | null;
  usageError: string | null;
  usageStartDate: string;
  usageEndDate: string;
  usageChartMode: "tokens" | "cost";
  usageDailyChartMode: "total" | "by-type";
  usageTimeZone: "local" | "utc";
  localAgentsLoading: boolean;
  localAgentsReport: import("./local-agents.js").LocalAgentsProbeReport | null;
  localAgentsError: string | null;
  cronLoading: boolean;
  cronJobs: CronJob[];
  cronStatus: CronStatus | null;
  cronError: string | null;
  cronForm: CronFormState;
  cronRunsJobId: string | null;
  cronRuns: CronRunLogEntry[];
  cronBusy: boolean;
  cronAddModalOpen: boolean;
  cronEditModalOpen: boolean;
  cronEditJobId: string | null;
  apiKeysLoading: boolean;
  apiKeys: import("./controllers/api-keys.ts").ApiKeyEntry[];
  apiKeysError: string | null;
  apiKeysBusy: boolean;
  apiKeysForm: import("./controllers/api-keys.ts").ApiKeyFormState;
  apiKeysFormModalOpen: boolean;
  apiKeysFormModalMode: "create" | "edit";
  apiKeysViewSecret: import("./controllers/api-keys.ts").ApiKeySecretView | null;
  apiKeysCreatedSecret: string | null;
  apiKeysExamplesModalOpen: boolean;
  skillsLoading: boolean;
  skillsReport: SkillStatusReport | null;
  skillsError: string | null;
  skillsFilter: string;
  skillEdits: Record<string, string>;
  skillMessages: Record<string, SkillMessage>;
  skillsBusyKey: string | null;
  skillsAddPanel: import("./views/skill-create-modals.ts").SkillAddPanel;
  skillsUploadStep: number;
  skillsUploadFile: File | null;
  skillsUploadAnalyze: import("./controllers/skill-create.ts").SkillAnalyzeResult | null;
  skillsUploadMeta: import("./controllers/skill-create.ts").SkillUploadMeta;
  skillsUploadError: string | null;
  skillsUploadTemplate: string | null;
  skillsUploadBusy: boolean;
  skillsCreativeScenario: "free" | "upgrade";
  skillsCreativeMessages: import("./controllers/skill-create.ts").SkillComposeMessage[];
  skillsCreativeDraft: string;
  skillsCreativeFiles: import("./controllers/skill-create.ts").SkillComposeFile[];
  skillsCreativeInput: string;
  skillsCreativeReady: boolean;
  skillsCreativeSelectedFile: string | null;
  skillsViewMode: "list" | "card";
  skillsSelectedSkillKey: string | null;
  skillsSkillDocContent: string | null;
  skillsSkillDocLoading: boolean;
  skillsSkillDocError: string | null;
  // MCP
  mcpSelectedKey: string | null;
  mcpViewMode: "list" | "card";
  mcpAddModalOpen: boolean;
  mcpAddName: string;
  mcpAddDraft: Record<string, unknown>;
  mcpAddConnectionType: "stdio" | "url" | "service";
  mcpAddEditMode: "form" | "raw";
  mcpAddRawJson: string;
  mcpAddRawError: string | null;
  mcpEditMode: "form" | "raw";
  mcpEditConnectionType: "stdio" | "url" | "service";
  mcpFormDirty: boolean;
  mcpRawJson: string;
  mcpRawError: string | null;
  // Security (replaces sandbox)
  securityForm: import("./controllers/security.js").SecurityConfigForm | Record<string, unknown> | null;
  // Approvals
  approvalsLoading: boolean;
  approvalsResult: import("./controllers/approvals.js").ApprovalsListResult | null;
  approvalsError: string | null;
  approvalBannerVisible: boolean;
  approvalBannerPollInitialized: boolean;
  approvalBannerBaselineIds: string[];
  approvalBannerPendingCount: number;
  // Models
  modelsSelectedProvider: string | null;
  modelsProviderSearchQuery: string;
  modelsViewMode: "list" | "card";
  modelsFormDirty: boolean;
  modelsAddProviderModalOpen: boolean;
  modelsAddProviderForm: {
    providerId: string;
    displayName: string;
    baseUrl: string;
    apiKey: string;
    apiKeyPrefix: string;
  };
  modelsAddModelModalOpen: boolean;
  modelsAddModelForm: { modelId: string; modelName: string; contextWindow: string; maxTokens: string };
  modelsUseModelModalOpen: boolean;
  modelsUseModelModalProvider: string | null;
  modelsSaveError: string | null;
  modelLibraryCategory: "__all__" | "public" | "local";
  modelLibrarySelectedProvider: string | null;
  // Digital employees
  digitalEmployeesLoading: boolean;
  digitalEmployeesError: string | null;
  digitalEmployeesFilter: string;
  digitalEmployeesViewMode: "list" | "card";
  digitalEmployees: {
    id: string;
    name: string;
    description: string;
    prompt?: string;
    enabled?: boolean;
    createdAt?: number;
    builtin: boolean;
    skillIds?: string[];
    skillNames?: string[];
    mcpServerKeys?: string[];
  }[];
  digitalEmployeeCreateModalOpen: boolean;
  digitalEmployeeCreateName: string;
  digitalEmployeeCreateDescription: string;
  digitalEmployeeCreatePrompt: string;
  digitalEmployeeCreateError: string | null;
  digitalEmployeeCreateBusy: boolean;
  digitalEmployeeAdvancedOpen: boolean;
  digitalEmployeeCreateMcpMode: "builder" | "raw";
  digitalEmployeeCreateMcpJson: string;
  digitalEmployeeCreateMcpItems: import("./views/digital-employee.js").EmployeeMcpItem[];
  digitalEmployeeSkillUploadName: string;
  digitalEmployeeSkillUploadFiles: File[];
  digitalEmployeeSkillUploadError: string | null;
  digitalEmployeeSkillUploadBusy: boolean;
  digitalEmployeeEditModalOpen: boolean;
  digitalEmployeeEditId: string;
  digitalEmployeeEditName: string;
  digitalEmployeeEditDescription: string;
  digitalEmployeeEditPrompt: string;
  digitalEmployeeEditMcpJson: string;
  digitalEmployeeEditMcpMode: "builder" | "raw";
  digitalEmployeeEditMcpItems: import("./views/digital-employee.js").EmployeeMcpItem[];
  digitalEmployeeEditSkillNames: string[];
  digitalEmployeeEditSkillFilesToUpload: File[];
  digitalEmployeeEditSkillsToDelete: string[];
  digitalEmployeeEditEnabled: boolean;
  digitalEmployeeEditError: string | null;
  digitalEmployeeEditBusy: boolean;
  // Remote catalogs (employee market / skill library / tool library)
  employeeMarketLoadedOnce: boolean;
  employeeMarketLoading: boolean;
  employeeMarketError: string | null;
  employeeMarketQuery: string;
  employeeMarketCategory: string;
  employeeMarketCategoryDescendants: string[];
  employeeMarketViewMode: "list" | "card";
  employeeMarketItems: import("./controllers/remote-market.ts").EmployeeListItem[];
  employeeMarketSelectedId: number | string | null;
  employeeMarketSelectedDetail: import("./controllers/remote-market.ts").EmployeeDetail | null;
  employeeMarketInstalledRemoteIds: Set<string>;
  employeeMarketRemoteToLocal: Record<string, string>;
  employeeMarketInstallingId: string | null;
  employeeMarketQueryDebounceTimer: number | null;
  employeeMarketReloadVersion: number;

  skillLibraryLoadedOnce: boolean;
  skillLibraryLoading: boolean;
  skillLibraryError: string | null;
  skillLibraryQuery: string;
  skillLibraryCategory: string;
  skillLibraryCategoryDescendants: string[];
  skillLibraryStatus: string;
  skillLibraryItems: import("./controllers/remote-market.ts").SkillListItem[];
  skillLibrarySelectedFolder: string | null;
  skillLibrarySelectedDetail: import("./controllers/remote-market.ts").SkillDetail | null;
  skillLibraryInstallingFolder: string | null;
  skillLibraryInstallSuccess: string | null;
  skillLibraryEditModalOpen: boolean;
  skillLibraryEditSkillKey: string | null;
  skillLibraryEditFiles: string[];
  skillLibraryEditSelectedFile: string | null;
  skillLibraryEditContent: string;
  skillLibraryEditOriginalContent: string;
  skillLibraryEditLoading: boolean;
  skillLibraryEditSaving: boolean;
  skillLibraryEditError: string | null;
  skillLibraryEditSyntaxError: string | null;
  skillLibraryEditSuccessMessage: string | null;
  skillLibraryQueryDebounceTimer: number | null;
  skillLibraryReloadVersion: number;

  knowledgeVaultLoadedOnce: boolean;
  knowledgeVaultLoading: boolean;
  knowledgeVaultError: string | null;
  knowledgeVaultDir: string;
  knowledgeVaultFiles: import("./controllers/vault.ts").VaultFileEntry[];
  knowledgeVaultFolders: string[];
  knowledgeVaultExpandedFolders: string[];
  knowledgeVaultViewMode: import("./views/knowledge-vault.ts").KnowledgeVaultViewMode;
  knowledgeVaultSelectedPath: string | null;
  knowledgeVaultContent: string;
  knowledgeVaultContentLoading: boolean;
  knowledgeVaultEditorMode: import("./components/vault-editor.ts").VaultEditorMode;
  knowledgeVaultDraftContent: string;
  knowledgeVaultSaving: boolean;
  knowledgeVaultSaveMessage: string | null;
  knowledgeVaultSyncing: boolean;
  knowledgeVaultDirSaving: boolean;
  knowledgeVaultGraph: import("./controllers/vault.ts").VaultGraph | null;
  knowledgeVaultGraphLoading: boolean;
  knowledgeVaultQuery: string;
  knowledgeVaultSidebarWidth: number;
  knowledgeVaultFileCount: number;
  knowledgeVaultChunkCount: number;
  knowledgeVaultLastSyncedAt: string | null;
  knowledgeVaultSearchMode: import("./views/vault-search-panel.ts").VaultSearchMode;
  knowledgeVaultSearchResults: import("./controllers/vault.ts").VaultSearchHit[];
  knowledgeVaultSearchLoading: boolean;
  knowledgeVaultHighlightLine: number | null;
  knowledgeVaultSelectedFolderPath: string | null;
  knowledgeVaultItemModal: import("./views/vault-item-modal.ts").VaultItemModalState | null;
  knowledgeVaultItemModalSaving: boolean;
  knowledgeVaultItemModalError: string | null;

  toolLibraryLoadedOnce: boolean;
  toolLibraryLoading: boolean;
  toolLibraryError: string | null;
  toolLibraryQuery: string;
  toolLibraryCategory: string;
  toolLibraryCategoryDescendants: string[];
  toolLibraryItems: import("./controllers/remote-market.ts").McpListItem[];
  toolLibrarySelectedId: number | string | null;
  toolLibrarySelectedDetail: import("./controllers/remote-market.ts").McpDetail | null;
  toolLibraryInstalledRemoteIds: Set<string>;
  toolLibraryInstalledMcpMap: Map<number | string, string>;
  toolLibraryInstallingId: number | null;
  toolLibraryMcpEditModalOpen: boolean;
  toolLibraryMcpEditServerKey: string;
  toolLibraryQueryDebounceTimer: number | null;
  toolLibraryReloadVersion: number;

  tutorialsLoadedOnce: boolean;
  tutorialsLoading: boolean;
  tutorialsError: string | null;
  tutorialCategories: import("./controllers/remote-market.ts").EduCategory[];
  tutorialsActiveTab: import("./views/tutorials.ts").TutorialTab;
  tutorialsQuery: string;
  tutorialsSelectedCategoryId: number | null;
  tutorialsPlayingLink: string | null;
  tutorialsQueryDebounceTimer: number | null;

  aboutUninstallModalOpen: boolean;
  aboutUninstallMode: "program" | "full";
  aboutUninstallLoading: boolean;
  aboutUninstallError: string | null;
  aboutClearWorkspaceLoading: boolean;
  aboutClearWorkspaceError: string | null;
  debugLoading: boolean;
  debugStatus: StatusSummary | null;
  debugHealth: HealthSnapshot | null;
  debugModels: unknown[];
  debugHeartbeat: unknown;
  debugCallMethod: string;
  debugCallParams: string;
  debugCallResult: string | null;
  debugCallError: string | null;
  logsLoading: boolean;
  logsError: string | null;
  logsFile: string | null;
  logsEntries: LogEntry[];
  logsFilterText: string;
  logsLevelFilters: Record<LogLevel, boolean>;
  logsAutoFollow: boolean;
  logsTruncated: boolean;
  logsCursor: number | null;
  logsLastFetchAt: number | null;
  logsLimit: number;
  logsMaxBytes: number;
  logsAtBottom: boolean;
  chatHasAutoScrolled: boolean;
  eventLogBuffer: EventLogEntry[];
  themeMedia: MediaQueryList | null;
  themeMediaHandler: ((event: MediaQueryListEvent) => void) | null;
  swarmLoading: boolean;
  swarmError: string | null;
  swarmWorkspaces: import("./types/swarm-types.ts").SwarmWorkspace[];
  swarmActiveWorkspaceId: string | null;
  swarmMembers: import("./types/swarm-types.ts").SwarmMember[];
  swarmSelectedMemberId: string | null;
  swarmGraph: import("./types/swarm-types.ts").SwarmGraph | null;
  swarmHistory: import("./types/swarm-types.ts").SwarmHistoryEntry[];
  swarmInput: string;
  swarmSending: boolean;
  swarmStreamText: string;
  swarmReasoningText: string;
  swarmToolEntries: import("./controllers/swarm.ts").SwarmToolEntry[];
  swarmTreeCollapsed: Record<string, boolean>;
  swarmMidSplit: number;
  swarmEventsCollapsed: boolean;
  swarmVizScale: number;
  swarmVizOffsetX: number;
  swarmVizOffsetY: number;
  swarmPanelCollapsed: Record<string, boolean>;
  swarmCreateModalOpen: boolean;
  swarmCreateModalLabel: string;
  swarmDeleteModalOpen: boolean;
  swarmDeleteTargetId: string | null;
  swarmDeleteTargetLabel: string;
  swarmAddMemberModalOpen: boolean;
  swarmAddMemberEmployeeId: string;
  swarmAddMemberLabel: string;
  client: GatewayBrowserClient | null;
  approvalBannerPollInterval: number | null;
  refreshSessionsAfterChat: Set<string>;
  connect: () => void;
  setTab: (tab: Tab) => void;
  setTheme: (theme: ThemeMode, context?: ThemeTransitionContext) => void;
  applySettings: (next: UiSettings) => void;
  loadOverview: () => Promise<void>;
  loadAssistantIdentity: () => Promise<void>;
  loadCron: () => Promise<void>;
  handleWhatsAppStart: (force: boolean) => Promise<void>;
  handleWhatsAppWait: () => Promise<void>;
  handleWhatsAppLogout: () => Promise<void>;
  handleWeWorkQrStart: () => Promise<void>;
  handleWeWorkQrModalClose: () => void;
  handleWeixinQrStart: () => Promise<void>;
  handleWeixinQrModalClose: () => void;
  handleChannelConfigSave: () => Promise<void>;
  handleChannelConfigReload: () => Promise<void>;
  handleNostrProfileEdit: (accountId: string, profile: NostrProfile | null) => void;
  handleNostrProfileCancel: () => void;
  handleNostrProfileFieldChange: (field: keyof NostrProfile, value: string) => void;
  handleNostrProfileSave: () => Promise<void>;
  handleNostrProfileImport: () => Promise<void>;
  handleNostrProfileToggleAdvanced: () => void;
  handleExecApprovalDecision: (decision: "allow-once" | "allow-always" | "deny") => Promise<void>;
  dismissApprovalBanner: () => void;
  finishSetupWizard: () => Promise<void>;
  skipAllSetupWizard: () => Promise<void>;
  dismissSetupWizardWelcome: () => void;
  maybeStartSetupWizard: () => void;
  openSetupWizard: () => void;
  handleGatewayUrlConfirm: () => void;
  handleGatewayUrlCancel: () => void;
  handleConfigLoad: () => Promise<void>;
  handleConfigSave: () => Promise<void>;
  handleConfigApply: () => Promise<void>;
  handleConfigFormUpdate: (path: string, value: unknown) => void;
  handleConfigFormModeChange: (mode: "form" | "raw") => void;
  handleConfigRawChange: (raw: string) => void;
  handleInstallSkill: (key: string) => Promise<void>;
  handleUpdateSkill: (key: string) => Promise<void>;
  handleToggleSkillEnabled: (key: string, enabled: boolean) => Promise<void>;
  handleUpdateSkillEdit: (key: string, value: string) => void;
  handleSaveSkillApiKey: (key: string, apiKey: string) => Promise<void>;
  handleCronToggle: (jobId: string, enabled: boolean) => Promise<void>;
  handleCronRun: (jobId: string) => Promise<void>;
  handleCronRemove: (jobId: string) => Promise<void>;
  handleCronAdd: () => Promise<void>;
  handleCronRunsLoad: (jobId: string) => Promise<void>;
  handleCronFormUpdate: (path: string, value: unknown) => void;
  handleSessionsLoad: () => Promise<void>;
  handleSessionsPatch: (key: string, patch: unknown) => Promise<void>;
  handleLoadNodes: () => Promise<void>;
  handleLoadPresence: () => Promise<void>;
  handleLoadSkills: () => Promise<void>;
  handleLoadDebug: () => Promise<void>;
  handleLoadLogs: () => Promise<void>;
  handleDebugCall: () => Promise<void>;
  handleRunUpdate: () => Promise<void>;
  setPassword: (next: string) => void;
  setSessionKey: (next: string) => void;
  setChatMessage: (next: string) => void;
  handleSendChat: (messageOverride?: string, opts?: { restoreDraft?: boolean; refreshSessions?: boolean }) => Promise<void>;
  handleAbortChat: () => Promise<void>;
  removeQueuedMessage: (id: string) => void;
  handleChatScroll: (event: Event) => void;
  resetToolStream: () => void;
  resetChatScroll: () => void;
  exportLogs: (lines: string[], label: string) => void;
  handleLogsScroll: (event: Event) => void;
  handleOpenSidebar: (content: string) => void;
  handleCloseSidebar: () => void;
  handleSplitRatioChange: (ratio: number) => void;
  handleNativePromptInput: (value: string) => void;
  handleNativeDialogConfirm: () => void;
  handleNativeDialogCancel: () => void;
  refreshWindowMaximised: () => Promise<void>;
  handleWindowMinimise: () => void;
  handleWindowToggleMaximise: () => void;
  handleWindowClose: () => void;
  handleTopbarDoubleClick: (event: MouseEvent) => void;
};
